### ISSUE TITLE
Add Datatang English Emotional Speech Dataset

### ISSUE THREAD

**Issue by SuperKogito** [SuperKogito/SER-datasets#22]
- Add Datatang English Emotional Speech Data
- Dataset: https://www.kaggle.com/datasets/datatangai/english-emotional-speech-data-by-microphone

**Comment by bagustris** [comment]
@SuperKogito 
The link is broken; perhaps the dataset become proprietary.

**Comment by SuperKogito** [comment]
The dataset is proprietary indeed https://www.datatang.ai/datasets/179
so this is dropped, as it does not fit the "at least free for research" criteria that we are following here. Thank you :)
