### ISSUE TITLE
Problem with LSSED

### ISSUE THREAD

**Issue by bagustris** [SuperKogito/SER-datasets#52]
@SuperKogito 
In a recent release, [LSSED](https://github.com/tobefans/LSSED) is included in the list. However, I think, It didn't belong to the following criteria:

- The dataset should be available for researchers for free.  
-  The information about the dataset must be accessible for verification.

The audio files are not shared (not available), only feature files. It is also difficult to get access (not accessible).

**Comment by SuperKogito** [comment]
thank you for catching this. I think I fell into the copy paste trap. 
I would say the dataset stays in the list as we included restricted/ closed access datasets before. 
However, I will need to correct the metadata (language, access, etc.) of the dataset.
