### ISSUE TITLE
add/ inspect MuSe-CaR (Multimodal Sentiment Analysis in Car Reviews)

### ISSUE THREAD

**Issue by SuperKogito** [SuperKogito/SER-datasets#62]
[MuSe-CaR (Multimodal Sentiment Analysis in Car Reviews)](https://paperswithcode.com/dataset/muse-car)

**Comment by bagustris** [comment]
@SuperKogito 
This dataset is already added.

![image](https://github.com/SuperKogito/SER-datasets/assets/3158361/60d2fdc4-95c2-4348-81ce-257e6a8ebf20)

**Comment by SuperKogito** [comment]
Thank you for catching this :+1:
